import type { Metadata } from 'next'
import './globals.css'
import { ThemeProvider } from '@/components/theme-provider'
import localFont from 'next/font/local'
 
// Font files can be colocated inside of `app`
const euclidCircular = localFont({ src: '../../public/fonts/EuclidCircular.ttf', display: 'swap' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeProvider
      attribute="class"
      defaultTheme="system">
      <body className={euclidCircular.className}>
        {children}
      </body>
      </ThemeProvider>
    </html>
  )
}
